site_name: Typer-TinyDB
site_url: https://arnos-stuff.github.io/

nav:
    - Home: index.md
    - Commands: commands.md
    - Contributing: future-work.md
    - About: about.md
theme:
  name: dracula
  locale: en
  highlightjs: true

dev_addr: "127.0.0.1:8000"

site_dir: typer-tinydb/site

repo_url: 'https://github.com/arnos-stuff/typer-tinydb/wiki'
edit_uri_template: '{path_noext}/_edit'

markdown_extensions:
    - toc:
        permalink: True