site_name: Typer-TinyDB
nav:
    - Home: index.md
    - Commands: commands.md
    - Contributing: future-work.md
    - About: about.md
theme:
  name: dracula
  locale: en
  highlightjs: true

repo_url: 'https://github.com/arnos-stuff/typer-tinydb/wiki'
edit_uri_template: '{path_noext}/_edit'

markdown_extensions:
    - toc:
        permalink: True