# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0
  python: circleci/python@2.1.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  install_and_test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          cache-version: v2
          include-python-in-cache-key: false
      - run:
          command: |
            poetry run pytest --cov=./ --cov-report=xml
            sudo mkdir /workspace
            sudo mv coverage.xml /workspace/coverage.xml
          name: Test it
      - persist_to_workspace:
          name: Persist the codecov XML
          root: /workspace
          paths:
            - coverage.xml
  codecov-job:
    docker:
      # replace with your preferred image
      - image: cimg/python:3.10
    steps:
      - attach_workspace:
          name: fetch the codecov file
          at: /tmp/workspace
      - codecov/upload:
          file: /tmp/workspace/coverage.xml
          token: CODECOV_REPO_TOKEN

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  test-ci:
    jobs:
      - install_and_test
      - codecov-job:
          requires:
            - install_and_test
